# Generated by Django 4.2 on 2023-09-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userpic',
            field=models.ImageField(blank=True, null=True, upload_to='userpics/'),
        ),
    ]
