# Generated by Django 4.2 on 2023-11-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='payment_completed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='placed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='processing',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PL', 'Placed'), ('PR', 'Processing'), ('CO', 'Completed'), ('CA', 'Cancelled')], default='PL', max_length=2),
        ),
    ]
